### ISSUE TITLE
Modularise The bot

### ISSUE THREAD

**Issue by mathematicalninja** [mathematicalninja/Quirk-A-Bot#2]
Switch from one central js file to a module approach, with a wake up, and then the various uses for Quirk-A-Bot (optionally add in a .env reference for each allowing various uses to be turned on/off at user end.

**Comment by eliasm307** [comment]
@mathematicalninja  This is a good idea, this was part of the initial recommendations I had but didn't want to change too much. I can have a look into this when pull-request #6 is resolved
